apiVersion: v1
kind: Service
metadata:  
  name: gnet-svc 
  namespace: grupoguma
spec:
  selector:    
    app: gnet-app
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10000